### ISSUE TITLE
 Reduce the CPU usage in modbus master rtu mode

### ISSUE THREAD

**Issue by azat385** [mushorg/modbus-tk#2]
How to  reduce the CPU usage in modbus master rtu mode?
(im running modbus-tk on raspberry pi model B+ and now it takes ~53-55% of CPU)
i tried to follow http://stackoverflow.com/a/21459211/3882432 modified the modbus_rtu.py and rerun python setup.py install
it didnt help.

what else can be done?

Thank you.

**Comment by glaslos** [comment]
Sorry for the late response. Can you share your code?

**Comment by azat385** [comment]
Sorry for the mazy code:
https://github.com/azat385/rpiplc/blob/master/sc6tk.py

it was done 2 years ago )

i have tried to modify code as in EDIT section of [stackoverflow: Python modbus library](http://stackoverflow.com/questions/17081442/python-modbus-library/21459211#21459211)
```
def _recv(self, expected_length=-1):
     """Receive the response from the slave"""
     response = ""
     read_bytes = "dummy"
     iterCnt = 0
     while read_bytes:
         if iterCnt == 0:
             read_bytes = self._serial.read(expected_length)  # reduces CPU load for longer frames; serial port timeout is used anyway 
         else:
             read_bytes = self._serial.read(1)
         response += read_bytes
         if len(response) >= expected_length >= 0:
             #if the expected number of byte is received consider that the response is done
             #improve performance by avoiding end-of-response detection by timeout
             break
         iterCnt += 1
```

**Comment by glaslos** [comment]
Please report to https://github.com/ljean/modbus-tk
