### ISSUE TITLE
RS485 Sniffer

### ISSUE THREAD

**Issue by MrD2** [mushorg/modbus-tk#3]
Is it possible to make a Sniffer of a RS485 BUS?

**Comment by glaslos** [comment]
Sure. You just have to skip the TCP layer when you want to parse the modbus packets from your serial console.

**Comment by MrD2** [comment]
As i see, the only way o make the sniffer is to use some parts of the core code.... As if i use the Master i am obliged to Send before i can Receive.... As the purpose of the sniffer is to Ear everything and parse it acordingly, i think this is the way?


`import time
import serial
import sys
from struct import *

import modbus_tk.defines as tkCst
import modbus_tk.modbus_rtu as tkRtu

portName = '/dev/ttyUSB0'
portParity = serial.PARITY_EVEN
baudrate = 9600
timeoutSp=0.25
print "timeout: %s [s]" % timeoutSp

maxRTUpacket=256


sniffer = tkRtu.RtuMaster(serial.Serial(port=portName, baudrate=baudrate, parity=portParity))
sniffer.set_timeout(timeoutSp)

listener = sniffer._make_query()

while 1:
	num_reg = 0
	#REQUEST
	msg = sniffer._recv(8)
	if msg != None and msg != "":
		if len(msg) == 8:
			#address, data = listener.parse_request(msg)
			id, type, req_address, num_reg, crc = unpack(">BBHHH", msg)
			print "REQUEST:  " + msg.encode('hex')
		else:
			continue
		#print "ADDRESS: " + str(address).encode('hex') + " DATA: " + str(data).encode('hex')
		
	if num_reg == 0:
		continue
	#REPLY
	bytes_to_read = 3+(num_reg*2)+2
	if maxRTUpacket < (bytes_to_read):
		continue
	msg = sniffer._recv(bytes_to_read)
	#address, data = listener.parse_response(msg)
	if msg != None and msg != "":
		print "RESPONSE: " + msg.encode('hex')
	
	#print "ADDRESS: " + str(address).encode('hex') + " DATA: " + str(data).encode('hex')`

I don't know much what the hook_calls do between some of the core code, that's why i am a little confused.... Either way, i try to parse the data received in `msg = sniffer._recv(bytes_to_read)`  and it breaks cause of CRC.... i tested and i think it is because of the delay while receiving bytes, it exits because of timeout and the message is not complete????

Does this `sniffer.set_timeout(timeoutSp)` sets the timeout for the serial.read is array or byte wise?

Sometime i get this issue here:
![image](https://cloud.githubusercontent.com/assets/5084445/17623256/015269b8-6097-11e6-9e23-988ae549479a.png)

Is there any easy way of doing this?

**Comment by glaslos** [comment]
Here is how we use Modbus: https://github.com/mushorg/conpot/blob/master/conpot/protocols/modbus/modbus_server.py#L82
