### ISSUE TITLE
unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by nickma82** [mushorg/modbus-tk#4]
Hi,
with pip's modbus-tk==0.5.4 I'm getting the following error after receiving a package like this `DEBUG - <- 0-2-0-0-0-4-1-2-1-1` [modbus.py:346](https://github.com/mushorg/modbus-tk/blob/b56f6e484b473172fbac2a753509a3cb8a86abe9/modbus_tk/modbus.py#L346)

And a couple of lines below that, the error `unpack requires a string argument of length 4` from [modbus.py:373](https://github.com/mushorg/modbus-tk/blob/b56f6e484b473172fbac2a753509a3cb8a86abe9/modbus_tk/modbus.py#L373): `result = struct.unpack(data_format, data)`

Further Infos: I'm reading a discrete_input from a modbus_tk.modbus_tcp.TcpServer - `DEBUG - -> 0-1-0-0-0-6-1-3-156-65-0-2`
Any Idea?

**Comment by glaslos** [comment]
In what context are you using modbus-tk? If you are not running Conpot, I'd recommend using the official version: https://github.com/ljean/modbus-tk
If you are using Conpot, we probably have to merge the changes from the official repo.

**Comment by nickma82** [comment]
Oh, well, not using Conpot, sorry for that.
